export const FETCH_CLIENTS_START = 'FETCH_CLIENTS_START'
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS'
export const FETCH_CLIENTS_FAIL = 'FETCH_CLIENTS_FAIL'

export const SELECT_CLIENT = 'SELECT_CLIENT'

export const FETCH_PETS_START = 'FETCH_PETS_START'
export const FETCH_PETS_SUCCESS = 'FETCH_PETS_SUCCESS'
export const FETCH_PETS_FAIL = 'FETCH_PETS_FAIL'

export const ADD_PET_START = 'ADD_PET_START'
export const ADD_PET_SUCCESS = 'ADD_PET_SUCCESS'
export const ADD_PET_FAIL = 'ADD_PET_FAIL'

export const SELECT_PET = 'SELECT_PET'

export const EDIT_PET_START = 'EDIT_PET_START'
export const EDIT_PET_SUCCESS = 'EDIT_PET_SUCCESS'
export const EDIT_PET_FAIL = 'EDIT_PET_FAIL'

export const DEL_PET_START = 'DEL_PET_START'
export const DEL_PET_SUCCESS = 'DEL_PET_SUCCESS'
export const DEL_PET_FAIL = 'DEL_PET_FAIL'

export const FETCH_CLINICS_START = 'FETCH_CLINICS_START'
export const FETCH_CLINICS_SUCCESS = 'FETCH_CLINICS_SUCCESS'
export const FETCH_CLINICS_FAIL = 'FETCH_CLINICS_FAIL'

export const SELECT_CLINIC = 'SELECT_CLINIC'

export const FETCH_DOCTORS_START = 'FETCH_DOCTORS_START'
export const FETCH_DOCTORS_SUCCESS = 'FETCH_DOCTORS_SUCCESS'
export const FETCH_DOCTORS_FAIL = 'FETCH_DOCTORS_FAIL'

export const SELECT_DOCTOR = 'SELECT_DOCTOR'

export const FETCH_ADMINS_START = 'FETCH_ADMINS_START'
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS'
export const FETCH_ADMINS_FAIL = 'FETCH_ADMINS_FAIL'

export const SELECT_ADMIN = 'SELECT_ADMIN'

export const FETCH_APPOINTMENTS_START = 'FETCH_APPOINTMENTS_START'
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS'
export const FETCH_APPOINTMENTS_FAIL = 'FETCH_APPOINTMENTS_FAIL'

export const SELECT_APPOINTMENT = 'SELECT_APPOINTMENT'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_ME_SUCCESS = 'AUTH_ME_SUCCESS'
export const AUTH_ME_FAIL = 'AUTH_ME_FAIL'

export const SET_PASSWORD_START = 'SET_PASSWORD_START'
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS'
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL'

export const EDIT_USER_START = 'EDIT_USER_START'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'

export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH'

export const ADD_APPOINTMENT_START = 'ADD_APPOINTMENT_START'
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS'
export const ADD_APPOINTMENT_FAIL = 'ADD_APPOINTMENT_FAIL'

export const DEL_APPOINTMENT_START = 'DEL_APPOINTMENT_START'
export const DEL_APPOINTMENT_SUCCESS = 'DEL_APPOINTMENT_SUCCESS'
export const DEL_APPOINTMENT_FAIL = 'DEL_APPOINTMENT_FAIL'


export const UPLOAD_PIC_START = 'UPLOAD_PIC_START'
export const UPLOAD_PIC_SUCCESS = 'UPLOAD_PIC_SUCCESS'
export const UPLOAD_PIC_FAIL = 'UPLOAD_PIC_FAIL'
